export const CREATE_PATIENT_PROFILE_BEGIN = 'CREATE_PROFILE_BEGIN';
export const CREATE_PATIENT_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PATIENT_PROFILE_FAILURE = 'CREATE_PROFILE_FAILURE';

export const CREATE_PROVIDER_PROFILE_BEGIN = 'CREATE_PROVIDER_PROFILE_BEGIN';
export const CREATE_PROVIDER_PROFILE_SUCCESS = 'CREATE_PROVIDER_PROFILE_SUCCESS';
export const CREATE_PROVIDER_PROFILE_FAILURE = 'CREATE_PROVIDER_PROFILE_FAILURE';

export const LOAD_PROFILE_BEGIN = 'LOAD_PROFILE_BEGIN';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE';

export const SAVE_PROFILE_BEGIN = 'SAVE_PROFILE_BEGIN';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAILURE = 'SAVE_PROFILE_FAILURE';

export const EDIT_PROFILE = 'EDIT_PROFILE';

export const SUBMIT_PDISURVEY_BEGIN = 'SUBMIT_PDISURVEY_BEGIN';
export const SUBMIT_PDISURVEY_SUCCESS = 'SUBMIT_PDISURVEY_SUCCESS';
export const SUBMIT_PDISURVEY_FAILURE = 'SUBMIT_PDISURVEY_FAILURE';

export const FETCH_PDISURVEYS_BEGIN = 'FETCH_PDISURVEYS_BEGIN'; 
export const FETCH_PDISURVEYS_SUCCESS = 'FETCH_PDISURVEYS_SUCCESS'; 
export const FETCH_PDISURVEYS_FAILURE = 'FETCH_PDISURVEYS_FAILURE'; 

export const SUBMIT_INTAKESURVEY_BEGIN = 'SUBMIT_INTAKESURVEY_BEGIN';
export const SUBMIT_INTAKESURVEY_SUCCESS = 'SUBMIT_INTAKESURVEY_SUCCESS';
export const SUBMIT_INTAKESURVEY_FAILURE = 'SUBMIT_INTAKESURVEY_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FETCH_DISPENSER_BEGIN = 'FETCH_DISPENSER_BEGIN'; 
export const FETCH_DISPENSER_SUCCESS = 'FETCH_DISPENSER_SUCCESS'; 
export const FETCH_DISPENSER_FAILURE = 'FETCH_DISPENSER_FAILURE'; 

export const ADD_PROFILE_MODULE_BEGIN = 'ADD_PROFILE_MODULE_BEGIN';
export const ADD_PROFILE_MODULE_SUCCESS = 'ADD_PROFILE_MODULE_SUCCESS';
export const ADD_PROFILE_MODULE_FAILURE = 'ADD_PROFILE_MODULE_FAILURE';

export const FETCH_PATIENTS_BEGIN = 'FETCH_ALL_PATIENTS_BEGIN'; 
export const FETCH_PATIENTS_SUCCESS = 'FETCH_ALL_PATIENTS_SUCCESS'; 
export const FETCH_PATIENTS_FAILURE = 'FETCH_ALL_PATIENTS_FAILURE'; 

export const FETCH_ROLES_BEGIN = 'FETCH_ROLES_BEGIN'; 
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS'; 
export const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE'; 

export const ADD_PATIENT_BEGIN = 'ADD_PATIENT_BEGIN';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_FAILURE = 'ADD_PATIENT_FAILURE'; 

export const REMOVE_PATIENT_BEGIN = 'REMOVE_PATIENT_BEGIN';
export const REMOVE_PATIENT_SUCCESS = 'REMOVE_PATIENT_SUCCESS';
export const REMOVE_PATIENT_FAILURE = 'REMOVE_PATIENT_FAILURE';

export const AUTH0_REGISTRATION_BEGIN = 'AUTH0_REGISTRATION_BEGIN'; 
export const AUTH0_REGISTRATION_SUCCESS = 'AUTH0_REGISTRATION_SUCCESS'; 
export const AUTH0_REGISTRATION_FAILURE = 'AUTH0_REGISTRATION_FAILURE'; 

export const ASSIGN_ROLES_BEGIN = 'ASSIGN_ROLES_BEGIN';
export const ASSIGN_ROLES_SUCCESS = 'ASSIGN_ROLES_SUCCESS';
export const ASSIGN_ROLES_FAILURE = 'ASSIGN_ROLES_FAILURE';

export const DELETE_PATIENT_BEGIN = 'DELETE_PATIENT_BEGIN';
export const DELETE_PATIENT_SUCCESS = 'DELETE_PATIENT_BEGIN';
export const DELETE_PATIENT_FAILURE = 'DELETE_PATIENT_FAILURE';

export const FETCH_ALL_PATIENTS_BEGIN = 'FETCH_ALL_PATIENTS_BEGIN';
export const FETCH_ALL_PATIENTS_SUCCESS = 'FETCH_ALL_PATIENTS_SUCCESS';
export const FETCH_ALL_PATIENTS_FAILURE = 'FETCH_ALL_PATIENTS_FAILURE';

export const FETCH_ALL_PROVIDERS_BEGIN = 'FETCH_ALL_PROVIDERS_BEGIN';
export const FETCH_ALL_PROVIDERS_SUCCESS = 'FETCH_ALL_PROVIDERS_SUCCESS';
export const FETCH_ALL_PROVIDERS_FAILURE = 'FETCH_ALL_PROVIDERS_FAILURE';

export const DELETE_PROVIDER_BEGIN = 'DELETE_PROVIDER_BEGIN';
export const DELETE_PROVIDER_SUCCESS = 'DELETE_PROVIDER_SUCCESS';
export const DELETE_PROVIDER_FAILURE = 'DELETE_PROVIDER_FAILURE';

export const COLLAPSE_SIDEBAR = 'COLLAPSE_SIDEBAR';
export const EXPAND_SIDEBAR = 'EXPAND_SIDEBAR';
export const SET_SIDEBAR_TOGGLE = 'SET_SIDEBAR_TOGGLE'; 

export const ADD_DISPENSER_CODE_BEGIN = 'ADD_DISPNESER_CODE_BEGIN'; 
export const ADD_DISPENSER_CODE_SUCCESS = 'ADD_DISPNESER_CODE_SUCCESS'; 
export const ADD_DISPENSER_CODE_FAILURE = 'ADD_DISPNESER_CODE_FAILURE'; 

export const REGISTER_NEW_USER_BEGIN = 'REGISTER_NEW_USER_BEGIN';
export const REGISTER_NEW_USER_SUCCESS = 'REGISTER_NEW_USER_SUCCESS';
export const REGISTER_NEW_USER_FAILURE = 'REGISTER_NEW_USER_FAILURE';

export const FETCH_ALL_CLINICS_BEGIN = 'FETCH_ALL_CLINICS_BEGIN';
export const FETCH_ALL_CLINICS_SUCCESS = 'FETCH_ALL_CLINICS_SUCCESS';
export const FETCH_ALL_CLINICS_FAILURE = 'FETCH_ALL_CLINICS_FAILURE';

export const FETCH_ALL_PROVIDERS_AT_CLINIC_BEGIN =   'FETCH_ALL_PROVIDERS_AT_CLINIC_BEGIN';
export const FETCH_ALL_PROVIDERS_AT_CLINIC_SUCCESS = 'FETCH_ALL_PROVIDERS_AT_CLINIC_SUCCESS';
export const FETCH_ALL_PROVIDERS_AT_CLINIC_FAILURE = 'FETCH_ALL_PROVIDERS_AT_CLINIC_FAILURE'; 

export const ADD_CHECKIN_BEGIN = 'ADD_CHECKIN_BEGIN'; 
export const ADD_CHECKIN_SUCCESS = 'ADD_CHECKIN_SUCCESS'; 
export const ADD_CHECKIN_FAILURE = 'ADD_CHECKIN_FAILURE'; 

export const REGISTER_NEW_CLINIC_BEGIN = 'REGISTER_NEW_CLINIC_BEGIN';
export const REGISTER_NEW_CLINIC_SUCCESS = 'REGISTER_NEW_CLINIC_SUCCESS';
export const REGISTER_NEW_CLINIC_FAILURE = 'REGISTER_NEW_CLINIC_FAILURE';

export const VALIDATE_REGISTER_CODE_BEGIN = 'VALIDATE_REGISTER_CODE_BEGIN';
export const VALIDATE_REGISTER_CODE_SUCCESS = 'VALIDATE_REGISTER_CODE_SUCCESS';
export const VALIDATE_REGISTER_CODE_FAILURE = 'VALIDATE_REGISTER_CODE_FAILURE';

export const UPDATE_MEDICAL_DATA_BEGIN = 'UPDATE_MEDICAL_DATA_BEGIN';
export const UPDATE_MEDICAL_DATA_SUCCESS = 'UPDATE_MEDICAL_DATA_SUCCESS';
export const UPDATE_MEDICAL_DATA_FAILURE = 'UPDATE_MEDICAL_DATA_FAILURE';


