export const CREATE_PROFILE_BEGIN = 'CREATE_PROFILE_BEGIN';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAILURE = 'CREATE_PROFILE_FAILURE';

export const LOAD_PROFILE_BEGIN = 'LOAD_PROFILE_BEGIN';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE';

export const SAVE_PROFILE_BEGIN = 'SAVE_PROFILE_BEGIN';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAILURE = 'SAVE_PROFILE_FAILURE';

export const EDIT_PROFILE = 'EDIT_PROFILE';

export const SUBMIT_SURVEY_BEGIN = 'SUBMIT_SURVEY_BEGIN';
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS';
export const SUBMIT_SURVEY_FAILURE = 'SUBMIT_SURVEY_FAILURE';

export const FETCH_PDISURVEYS_BEGIN = 'FETCH_PDISURVEYS_BEGIN'; 
export const FETCH_PDISURVEYS_SUCCESS = 'FETCH_PDISURVEYS_SUCCESS'; 
export const FETCH_PDISURVEYS_FAILURE = 'FETCH_PDISURVEYS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FETCH_DISPENSES_BEGIN = 'FETCH_DISPENSES_BEGIN'; 
export const FETCH_DISPENSES_SUCCESS = 'FETCH_DISPENSES_SUCCESS'; 
export const FETCH_DISPENSES_FAILURE = 'FETCH_DISPENSES_FAILURE'; 

export const ADD_PROFILE_MODULE_BEGIN = 'ADD_PROFILE_MODULE_BEGIN';
export const ADD_PROFILE_MODULE_SUCCESS = 'ADD_PROFILE_MODULE_SUCCESS';
export const ADD_PROFILE_MODULE_FAILURE = 'ADD_PROFILE_MODULE_FAILURE';