export const SAVE_PROFILE = 'SAVE_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const SUBMIT_SURVEY = 'SUBMIT_SURVEY'; 
export const FETCH_PDISURVEYS_BEGIN = 'FETCH_PDISURVEYS_BEGIN'; 
export const FETCH_PDISURVEYS_SUCCESS = 'FETCH_PDISURVEYS_SUCCESS'; 
export const FETCH_PDISURVEYS_FAILURE = 'FETCH_PDISURVEYS_FAILURE'; 