export const SAVE_PROFILE = 'SAVE_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';

export const SUBMIT_SURVEY_BEGIN = 'SUBMIT_SURVEY_BEGIN';
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS';
export const SUBMIT_SURVEY_FAILURE = 'SUBMIT_SURVEY_FAILURE';

export const SUBMIT_SURVEY = 'SUBMIT_SURVEY';  

export const FETCH_PDISURVEYS_BEGIN = 'FETCH_PDISURVEYS_BEGIN'; 
export const FETCH_PDISURVEYS_SUCCESS = 'FETCH_PDISURVEYS_SUCCESS'; 
export const FETCH_PDISURVEYS_FAILURE = 'FETCH_PDISURVEYS_FAILURE'; 

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FETCH_DISPENSES_BEGIN = 'FETCH_DISPENSES_BEGIN'; 
export const FETCH_DISPENSES_SUCCESS = 'FETCH_DISPENSES_SUCCESS'; 
export const FETCH_DISPENSES_FAILURE = 'FETCH_DISPENSES_FAILURE'; 
